// Unity / VRChat material export: a material JSON sidecar plus a shader that
// reproduces SA2's stage/model shading.
//
// SA2 materials are simple by modern standards: a single texture modulated by
// per-vertex colour, optionally unlit (most stage geometry is baked-unlit),
// optionally spherical environment-mapped (chrome/water), with a GX blend mode.
// The shader below exposes exactly those knobs and nothing else, so it drops
// straight into a VRChat world without GrabPass or other banned features.
#include "sa2core.h"

#include <cstdio>
#include <cstring>
#include <map>
#include <vector>
#include <string>

namespace sa2 {

// GX blend factor -> Unity Blend enum name.
static const char* gx_blend(int f) {
    switch (f) {
        case 0: return "Zero";
        case 1: return "One";
        case 2: return "SrcColor";
        case 3: return "OneMinusSrcColor";
        case 4: return "SrcAlpha";
        case 5: return "OneMinusSrcAlpha";
        case 6: return "DstAlpha";
        case 7: return "OneMinusDstAlpha";
        default: return "SrcAlpha";
    }
}

struct MatKey {
    int tex;
    bool alpha, unlit, env, twosided;
    int bsrc, bdst;
    uint32_t diffuse;
    bool operator<(const MatKey& o) const {
        return std::tie(tex, alpha, unlit, env, twosided, bsrc, bdst, diffuse) <
               std::tie(o.tex, o.alpha, o.unlit, o.env, o.twosided, o.bsrc, o.bdst, o.diffuse);
    }
};

static std::string json_escape(const std::string& s) {
    std::string o;
    for (char c : s) {
        if (c == '"' || c == '\\') { o += '\\'; o += c; }
        else if (c == '\n') o += "\\n";
        else o += c;
    }
    return o;
}

static const char* kShader = R"SHADER(// SA2 stage/model shader - reproduces Sonic Adventure 2 GameCube shading.
// VRChat-safe: no GrabPass, no custom lightmodes beyond ForwardBase/Add.
// Generated by sa2-extractor.
Shader "SA2/StageMaterial"
{
    Properties
    {
        _MainTex ("Texture", 2D) = "white" {}
        _Color ("Diffuse", Color) = (0.70,0.70,0.70,1)
        [Toggle(_UNLIT)] _Unlit ("Unlit (ignore scene light)", Float) = 1
        [Toggle(_ENVMAP)] _EnvMap ("Spherical env map", Float) = 0
        _EnvStrength ("Env strength", Range(0,2)) = 0.5
        [Toggle(_ALPHATEST)] _AlphaTest ("Alpha test", Float) = 1
        _Cutoff ("Alpha cutoff", Range(0,1)) = 0.5
        [Enum(UnityEngine.Rendering.BlendMode)] _SrcBlend ("Src blend", Float) = 5
        [Enum(UnityEngine.Rendering.BlendMode)] _DstBlend ("Dst blend", Float) = 10
        [Enum(UnityEngine.Rendering.CullMode)] _Cull ("Cull", Float) = 2
        [Enum(Off,0,On,1)] _ZWrite ("ZWrite", Float) = 1
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" "Queue"="Geometry" }
        Blend [_SrcBlend] [_DstBlend]
        Cull [_Cull]
        ZWrite [_ZWrite]
        Pass
        {
            Tags { "LightMode"="ForwardBase" }
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_fwdbase
            #pragma shader_feature_local _UNLIT
            #pragma shader_feature_local _ENVMAP
            #pragma shader_feature_local _ALPHATEST
            #include "UnityCG.cginc"
            #include "AutoLight.cginc"
            struct appdata { float4 vertex:POSITION; float3 normal:NORMAL; float2 uv:TEXCOORD0; float4 color:COLOR; };
            struct v2f {
                float4 pos:SV_POSITION; float2 uv:TEXCOORD0; float4 color:COLOR;
                float3 wnormal:TEXCOORD1; float3 wpos:TEXCOORD2;
            };
            sampler2D _MainTex; float4 _MainTex_ST; fixed4 _Color;
            float _EnvStrength, _Cutoff;
            v2f vert(appdata v){
                v2f o;
                o.pos = UnityObjectToClipPos(v.vertex);
                o.uv = TRANSFORM_TEX(v.uv, _MainTex);
                o.color = v.color;
                o.wnormal = UnityObjectToWorldNormal(v.normal);
                o.wpos = mul(unity_ObjectToWorld, v.vertex).xyz;
                return o;
            }
            fixed4 frag(v2f i):SV_Target{
                fixed4 tex = tex2D(_MainTex, i.uv);
                fixed4 col = tex * i.color * _Color;
                #ifdef _ALPHATEST
                    clip(col.a - _Cutoff);
                #endif
                #ifdef _ENVMAP
                    float3 v = normalize(_WorldSpaceCameraPos - i.wpos);
                    float3 r = reflect(-v, normalize(i.wnormal));
                    float2 suv = r.xy * 0.5 + 0.5;
                    col.rgb += tex2D(_MainTex, suv).rgb * _EnvStrength;
                #endif
                #ifndef _UNLIT
                    float3 n = normalize(i.wnormal);
                    float ndl = saturate(dot(n, normalize(_WorldSpaceLightPos0.xyz)));
                    float3 lit = _LightColor0.rgb * ndl + ShadeSH9(float4(n,1));
                    col.rgb *= max(lit, unity_AmbientSky.rgb + 0.2);
                #endif
                return col;
            }
            ENDCG
        }
    }
    Fallback "Unlit/Transparent"
}
)SHADER";

static const char* kApplyPy = R"PY(#!/usr/bin/env python3
"""Apply SA2 material JSON to an imported FBX in Blender.

    blender scene.blend --background --python apply_materials.py -- <base>.materials.json

Maps each material named "mat_N" in the JSON onto the matching Blender material,
setting base colour, blend mode, backface culling and (approximate) unlit/env.
For Unity, read the same JSON from a C# editor script and assign the
SA2/StageMaterial shader with the per-material keywords and blend values.
"""
import json, sys, os

def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]
    if not args:
        print("usage: apply_materials.py <base>.materials.json"); return 1
    data = json.load(open(args[0]))
    try:
        import bpy
    except ImportError:
        print(json.dumps(data, indent=2)); return 0
    for m in data["materials"]:
        mat = bpy.data.materials.get(m["name"])
        if not mat: continue
        mat.use_backface_culling = not m["double_sided"]
        mat.blend_method = "BLEND" if m["alpha_blend"] else ("CLIP" if m["alpha_test"] else "OPAQUE")
        if mat.use_nodes:
            bsdf = mat.node_tree.nodes.get("Principled BSDF")
            if bsdf:
                c = m["diffuse"]
                bsdf.inputs["Base Color"].default_value = (c[0], c[1], c[2], 1)
                if m["unlit"]:
                    bsdf.inputs["Specular IOR Level"].default_value = 0
    print(f"applied {len(data['materials'])} materials")
    return 0

if __name__ == "__main__":
    sys.exit(main())
)PY";

bool export_unity_materials(const std::string& dir, const std::string& base,
                            const Model& model, const std::vector<Image>& textures,
                            std::string* error) {
    auto open_w = [&](const std::string& p) -> FILE* {
        FILE* f = nullptr;
#ifdef _WIN32
        fopen_s(&f, p.c_str(), "wb");
#else
        f = fopen(p.c_str(), "wb");
#endif
        return f;
    };

    // collect unique materials
    std::map<MatKey, int> mats;
    std::vector<MatKey> order;
    for (const auto& p : model.parts) {
        MatKey k{p.texture_id, p.use_alpha, p.ignore_light, p.env_map,
                 p.double_sided, p.blend_src, p.blend_dst, p.diffuse};
        if (mats.find(k) == mats.end()) {
            mats[k] = (int)order.size();
            order.push_back(k);
        }
    }

    // material JSON
    std::string jpath = dir + "/" + base + ".materials.json";
    FILE* jf = open_w(jpath);
    if (!jf) { if (error) *error = "cannot write " + jpath; return false; }
    fprintf(jf, "{\n  \"model\": \"%s\",\n  \"shader\": \"SA2/StageMaterial\",\n",
            json_escape(base).c_str());
    fprintf(jf, "  \"materials\": [\n");
    for (size_t i = 0; i < order.size(); i++) {
        const MatKey& k = order[i];
        std::string texname = (k.tex >= 0 && k.tex < (int)textures.size())
                                  ? textures[k.tex].name : "";
        float dr = ((k.diffuse >> 16) & 0xFF) / 255.0f;
        float dg = ((k.diffuse >> 8) & 0xFF) / 255.0f;
        float db = (k.diffuse & 0xFF) / 255.0f;
        fprintf(jf,
            "    {\n"
            "      \"name\": \"mat_%zu\",\n"
            "      \"texture_id\": %d,\n"
            "      \"texture\": \"%s\",\n"
            "      \"diffuse\": [%.3f, %.3f, %.3f],\n"
            "      \"unlit\": %s,\n"
            "      \"env_map\": %s,\n"
            "      \"alpha_blend\": %s,\n"
            "      \"alpha_test\": %s,\n"
            "      \"double_sided\": %s,\n"
            "      \"blend_src\": \"%s\",\n"
            "      \"blend_dst\": \"%s\"\n"
            "    }%s\n",
            i, k.tex, json_escape(texname).c_str(), dr, dg, db,
            k.unlit ? "true" : "false", k.env ? "true" : "false",
            k.alpha ? "true" : "false", (!k.alpha) ? "true" : "false",
            k.twosided ? "true" : "false", gx_blend(k.bsrc), gx_blend(k.bdst),
            (i + 1 < order.size()) ? "," : "");
    }
    fprintf(jf, "  ]\n}\n");
    fclose(jf);

    // shader
    FILE* sf = open_w(dir + "/SA2Stage.shader");
    if (sf) { fwrite(kShader, 1, strlen(kShader), sf); fclose(sf); }

    // helper script
    FILE* pf = open_w(dir + "/apply_materials.py");
    if (pf) { fwrite(kApplyPy, 1, strlen(kApplyPy), pf); fclose(pf); }

    return true;
}

}  // namespace sa2
